let background = document.getElementById("body")
let change = document.getElementById("change")
let colorText = document.getElementById("color-text")
function change_color(color){
    background.style.backgroundColor = color
}

let colors = [
    'maroon',	
 	'darkred',	
 	'brown',
 	'firebrick'	,
 	'crimson',
 	'red',
 	'tomato',
    'coral',
 	'indianred',
 	'lightcoral',
 	'darksalmon',
 	'salmon',
 	'lightsalmon',
 	'orangered',
 	'darkorange',
 	'orange',
    'gold',
 	'darkgoldenrod',
    'goldenrod',
 	'palegoldenrod',
 	'darkkhaki',
 	'khaki',
 	'olive',
 	'yellow',
    'yellowgreen',
 	'darkolivegreen',
 	'olivedrab',
 	'lawngreen'	,
    'chartreuse',
    'greenyellow',
 	'darkgreen',
 	'green',
 	'forestgreen',
 	'lime',
 	'limegreen',
 	'lightgreen',
    'palegreen',
 	'darkseagreen',
    'mediumspringgreen',
 	'springgreen',
 	'seagreen',
    'mediumaquamarine',
 	'mediumseagreen',
 	'lightseagreen',
 	'darkslategray',
 	'teal',
 	'darkcyan',
 	'aqua',
 	'cyan',
 	'lightcyan',
 	'darkturquoise',
 	'turquoise',
 	'mediumturquoise',
 	'paleturquoise',
 	'aquamarine',
 	'powderblue',
 	'cadetblue',
 	'steelblue',
 	'cornflowerblue',
    'deepskyblue',
 	'dodgerblue',
 	'lightblue',
 	'skyblue',
 	'lightskyblue',
 	'midnightblue',
 	'navy',
    'darkblue',
    'mediumblue',
    'blue',
    'royalblue',
 	'blueviolet',
 	'indigo',
    'darkslateblue',
 	'slateblue',
 	'mediumslateblue',
 	'mediumpurple',
 	'darkmagenta',
 	'darkviolet',
 	'darkorchid',
 	'mediumorchid',
 	'purple',
 	'thistle',
 	'plum',
 	'violet',
 	'fuchsia',
 	'orchid',
 	'mediumvioletred',
 	'palevioletred',
 	'deeppink',
 	'hotpink',
 	'lightpink',
 	'pink',
 	'antiquewhite',
 	'beige',
 	'bisque',
 	'blanchedalmon',
 	'wheat',
 	'cornsilk',
 	'lemonchiffon',
 	'lightgoldenrodyellow',
 	'lightyellow',
 	'saddlebrown',
 	'sienna',
 	'chocolate',
 	'peru',
 	'sandybrown',
 	'burlywood',
 	'tan',
 	'rosybrown',
 	'moccasin',
 	'navajowhite',
 	'peachpuff',
 	'mistyrose',
 	'lavenderblush',
 	'linen',
 	'oldlace',
 	'papayawhip',
 	'seashell',
 	'mintcream',
 	'slategray',
 	'lightslategray',
 	'lightsteelblue',
 	'lavender',
 	'floralwhite',
 	'aliceblue',
 	'ghostwhite',
 	'honeydew',
 	'ivory',
    'azure',
 	'snow',
 	'dimgray',
 	'gray',
 	'darkgray',
 	'silver',
	'lightgray',
    'gainsboro',
 	'whitesmoke',
 	'white'
]

change.addEventListener("click", ()=>{
    let size = colors.length
    let random_number = 0
    random_number = Math.floor(Math.random()*size)
    console.log(random_number)
    colorText.innerHTML = colors[random_number];
    change_color(colors[random_number]);
});


